import {initializeApp} from "firebase-admin/app";
import {getFirestore,FieldValue} from "firebase-admin/firestore";
import {onCall,HttpsError,onRequest} from "firebase-functions/v2/https";
import {defineSecret} from "firebase-functions/params";
import {google} from "googleapis";
import crypto from "node:crypto";
initializeApp(); const db=getFirestore();
const CLIENT_ID=defineSecret("GOOGLE_OAUTH_CLIENT_ID"),CLIENT_SECRET=defineSecret("GOOGLE_OAUTH_CLIENT_SECRET"),OAUTH_REDIRECT=defineSecret("GOOGLE_OAUTH_REDIRECT_URI");
const scopes=["https://www.googleapis.com/auth/classroom.courses.readonly","https://www.googleapis.com/auth/classroom.coursework.me","https://www.googleapis.com/auth/classroom.coursework.students","https://www.googleapis.com/auth/classroom.profile.emails"];
const client=()=>new google.auth.OAuth2(CLIENT_ID.value(),CLIENT_SECRET.value(),OAUTH_REDIRECT.value());
async function requireTeacher(uid){const r=await db.doc(`roles/${uid}`).get();if(!r.exists||r.data().role!=="teacher")throw new HttpsError("permission-denied","Se requiere rol docente.")}
async function authorized(uid){const snap=await db.doc(`classroomTokens/${uid}`).get();if(!snap.exists)throw new HttpsError("failed-precondition","Conecte primero su cuenta de Classroom.");const c=client();c.setCredentials(snap.data());c.on("tokens",t=>db.doc(`classroomTokens/${uid}`).set({...t,updatedAt:FieldValue.serverTimestamp()},{merge:true}));return c}
export const startClassroomOAuth=onCall({secrets:[CLIENT_ID,CLIENT_SECRET,OAUTH_REDIRECT]},async req=>{if(!req.auth)throw new HttpsError("unauthenticated","Inicie sesión.");const state=crypto.randomBytes(24).toString("hex");await db.doc(`oauthStates/${state}`).set({uid:req.auth.uid,expiresAt:Date.now()+600000});return {url:client().generateAuthUrl({access_type:"offline",prompt:"consent",scope:scopes,state,include_granted_scopes:true})}});
export const classroomOAuthCallback=onRequest({secrets:[CLIENT_ID,CLIENT_SECRET,OAUTH_REDIRECT]},async(req,res)=>{try{const {code,state}=req.query;const s=await db.doc(`oauthStates/${state}`).get();if(!s.exists||s.data().expiresAt<Date.now())throw new Error("Estado OAuth inválido o vencido.");const {tokens}=await client().getToken(code);await db.doc(`classroomTokens/${s.data().uid}`).set({...tokens,updatedAt:FieldValue.serverTimestamp()},{merge:true});await s.ref.delete();res.redirect("/docente.html#classroom")}catch(e){res.status(400).send(`No fue posible conectar Classroom: ${e.message}`)}});
export const createCoursework=onCall({secrets:[CLIENT_ID,CLIENT_SECRET,OAUTH_REDIRECT]},async req=>{if(!req.auth)throw new HttpsError("unauthenticated","Inicie sesión.");await requireTeacher(req.auth.uid);const {courseId,title,description,dueDate,maxPoints=100,linkUrl}=req.data||{};if(!courseId||!title)throw new HttpsError("invalid-argument","Faltan courseId o title.");const auth=await authorized(req.auth.uid);const classroom=google.classroom({version:"v1",auth});const work={title,description,workType:"ASSIGNMENT",state:"PUBLISHED",maxPoints,materials:linkUrl?[{link:{url:linkUrl}}]:[]};if(dueDate){const d=new Date(dueDate);work.dueDate={year:d.getUTCFullYear(),month:d.getUTCMonth()+1,day:d.getUTCDate()};work.dueTime={hours:23,minutes:59}}
  const {data}=await classroom.courses.courseWork.create({courseId,requestBody:work});await db.doc(`coursework/${data.id}`).set({courseId,courseWorkId:data.id,title,creatorUid:req.auth.uid,alternateLink:data.alternateLink||"",createdAt:FieldValue.serverTimestamp()});return data});
export const submitEvidence=onCall({secrets:[CLIENT_ID,CLIENT_SECRET,OAUTH_REDIRECT]},async req=>{if(!req.auth)throw new HttpsError("unauthenticated","Inicie sesión.");const {courseId,courseWorkId,submissionId,evidenceUrl}=req.data||{};const auth=await authorized(req.auth.uid);const classroom=google.classroom({version:"v1",auth});if(evidenceUrl)await classroom.courses.courseWork.studentSubmissions.modifyAttachments({courseId,courseWorkId,id:submissionId,requestBody:{addAttachments:[{link:{url:evidenceUrl,title:"Evidencia Misión NEXUS"}}]}});await classroom.courses.courseWork.studentSubmissions.turnIn({courseId,courseWorkId,id:submissionId});return {status:"TURNED_IN"}});
export const syncGrade=onCall({secrets:[CLIENT_ID,CLIENT_SECRET,OAUTH_REDIRECT]},async req=>{if(!req.auth)throw new HttpsError("unauthenticated","Inicie sesión.");await requireTeacher(req.auth.uid);const {courseId,courseWorkId,submissionId,grade,returnToStudent=true}=req.data||{};const auth=await authorized(req.auth.uid);const classroom=google.classroom({version:"v1",auth});await classroom.courses.courseWork.studentSubmissions.patch({courseId,courseWorkId,id:submissionId,updateMask:"draftGrade,assignedGrade",requestBody:{draftGrade:grade,assignedGrade:grade}});if(returnToStudent)await classroom.courses.courseWork.studentSubmissions.return({courseId,courseWorkId,id:submissionId});return {status:"RETURNED",grade}});
