import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const platform=fs.readFileSync('public/course/platform-local.js','utf8');
const backend=fs.readFileSync('backend/app.py','utf8');
const pages=fs.readFileSync('.github/workflows/deploy-pages.yml','utf8');
const guide=fs.readFileSync('DESPLIEGUE_GITHUB_RENDER.md','utf8');
test('frontend acepta API remota configurable',()=>{assert.match(platform,/NEXUS_CONFIG/);assert.match(platform,/apiBase/)});
test('backend habilita CORS configurable',()=>{assert.match(backend,/CORSMiddleware/);assert.match(backend,/NEXUS_ALLOWED_ORIGINS/)});
test('backend admite directorio de datos configurable',()=>{assert.match(backend,/NEXUS_DATA_DIR/)});
test('GitHub Pages exige NEXUS_API_BASE',()=>{assert.match(pages,/NEXUS_API_BASE/);assert.match(pages,/runtime-config\.js/);assert.match(pages,/onrender\.com/)});
test('guía Render conserva comandos FastAPI',()=>{assert.match(guide,/pip install -r backend\/requirements\.txt/);assert.match(guide,/uvicorn backend\.app:app/);assert.match(guide,/nexus18-api\.onrender\.com/)});
