import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";import vm from "node:vm";import path from "node:path";
const root=path.resolve("public/course"),read=f=>fs.readFileSync(path.join(root,f),"utf8");
function data(){const context={window:{}};vm.createContext(context);vm.runInContext(read("course-data.js"),context);vm.runInContext(read("visual-lessons-data.js"),context);return context.window.NEXUS_VISUAL_LESSONS;}
test("las seis unidades contienen treinta lecciones híbridas",()=>{const v=data();assert.equal(Object.keys(v).length,30);for(let u=1;u<=6;u++)assert.equal(Object.keys(v).filter(id=>id.startsWith(`u${u}l`)).length,5,`Unidad ${u}`)});
test("cada lámina conserva ilustración, texto e interacción",()=>{for(const [id,d] of Object.entries(data())){assert.ok(d.title&&d.hook&&d.takeaway,`${id}: núcleo conceptual`);assert.equal(d.visual.length,4,`${id}: cuatro elementos explorables`);assert.equal(d.steps.length,4,`${id}: mapa de cuatro pasos`);assert.equal(d.challenge.options.length,4,`${id}: interacción`);assert.ok(Number.isInteger(d.challenge.answer));assert.ok(d.image&&d.imageAlt&&d.typical&&d.limit&&d.lab);assert.ok(fs.existsSync(path.join(root,d.image)),`${id}: ilustración disponible`)}});
test("el portal carga datos, estilos y ruta híbrida",()=>{const h=read("estudiante.html"),a=read("app.js");assert.match(h,/visual-lessons\.css/);assert.match(h,/visual-lessons-data\.js/);assert.match(a,/type==="visual"\?visualLessonHybridView\(id\)/);assert.match(a,/data-visual-answer/);assert.match(a,/data-visual-node/)});
test("la experiencia híbrida es visible desde el Centro de mando",()=>{const a=read("app.js"),css=read("styles.css");assert.match(a,/experiencia híbrida/);assert.match(a,/Observa\. Comprende\. Experimenta\. Construye\./);assert.match(a,/home-visual-preview/);assert.match(a,/visual-unit-grid/);assert.match(a,/Ver lámina/);assert.match(css,/\.home-visual-preview/);assert.match(css,/\.visual-unit-card/)});
test("la navegación visual permanece dentro de cada unidad",()=>{const a=read("app.js");assert.match(a,/ids=u\.lessons\.map\(l=>l\.id\)/);assert.match(a,/data-nav="game\/\$\{u\.id\}"/)});
test("las láminas son responsivas y respetan movimiento reducido",()=>{const css=read("visual-lessons.css");assert.match(css,/@media\(max-width:560px\)/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/)});
